Repository mniedermaier/CybICS, pull requests merged in 2025-01, with the labels that each got.

#79 Mount .ssh folder for git private key auth
  .devcontainer/virtual/docker-compose.yml
Labels: enhancement

#84 Updating install script for the raspberry pi
  software/installRPI.sh
Labels: bug, enhancement

#85 Reboot fix
  software/installRPI.sh
Labels: bug

#88 Fixing OpenPLC build:
  software/OpenPLC/Dockerfile
Labels: bug, dependencies
